### PR TITLE
Fix: Updated db config loading to account for sections

### LINKED ISSUE #1624: Allow users to manually tweak RocksDb Options
### Description
Inside `mainnetdb` folder there is an Options file. It has all rocksdb configurations. Currently every time one restarts IRI, its contents is being replaced by hard coded options.
We want to ignore the hardcoded options in case the Options file is present.

### Motivation
One would like to tune RocksDb performance without changing java code.
Anyone in the community could fine settings that are good for him.

### Requirements
1. If options file is missing use hardcoded options
2. Else use options in file

### PR DESCRIPTION
**Pull request by kwek20**
# Description
Copy/pasting the OPTIONS file in rocksdb in place of the config file we use should work.
However previously, sections were not supported, resulting in `null` and default options beeing loaded.

This adds the ability to load from both a partial or a full OPTIONS file

Fixes #1624

## Type of change
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?
Loaded both a OPTIONS file from another location, and a small config file

# Checklist:
- [X] My code follows the style guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java [hunk 1]
```diff
@@ -598,4 +607,31 @@ private DBOptions createOptions(String logPath, String configFile) throws IOExce
...
+    // https://stackoverflow.com/a/41084504/4512850 -ish
+    private static Map<String, Properties> parseINI(InputStream stream) throws IOException {
+        Map<String, Properties> result = new HashMap<>();
+        
+        @SuppressWarnings("serial")
+        Properties p = new Properties() {
+
+            private Properties section;
+
+            public synchronized Object put(Object key, Object value) {
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java]: add `@Override` annotation please

File: src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java [hunk 2]
```diff
@@ -598,4 +607,31 @@ private DBOptions createOptions(String logPath, String configFile) throws IOExce
 
         return options;
     }
+    
+    // https://stackoverflow.com/a/41084504/4512850 -ish
+    private static Map<String, Properties> parseINI(InputStream stream) throws IOException {
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java]: I think you can make this public and move it to `IotaIOUtils`

Could be useful so why not?
