### PR TITLE
Make TCPNeighbor send() synchronized to prevent queue overflows

### LINKED ISSUE #837: The synchronization is stuck
Version 1.4.2.4. I have a problem. The synchronization is stuck after 1-2 hours at 427434 block.
Log from node
```

ota-mainnet-node | 06/25 16:09:48.566 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #559118 to #559119
iota-mainnet-node | 06/25 16:09:52.656 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3293 , toReply = 0 / totalTransactions = 1603690
iota-mainnet-node | 06/25 16:10:02.657 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 4 , toBroadcast = 0 , toRequest = 3209 , toReply = 0 / totalTransactions = 1605418
iota-mainnet-node | 06/25 16:10:17.657 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3157 , toReply = 0 / totalTransactions = 1608201
iota-mainnet-node | 06/25 16:10:27.658 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 1 , toRequest = 3165 , toReply = 1 / totalTransactions = 1609771
iota-mainnet-node | 06/25 16:10:42.658 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3222 , toReply = 0 / totalTransactions = 1612906
iota-mainnet-node | 06/25 16:10:48.644 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #559119 to #559120
iota-mainnet-node | 06/25 16:10:52.659 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3277 , toReply = 0 / totalTransactions = 1614501
iota-mainnet-node | 06/25 16:11:01.458 [pool-6-thread-1] INFO  com.iota.iri.network.Node - RecentSeenBytes cache hit/miss ratio: 11881/38119
iota-mainnet-node | 06/25 16:11:07.659 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3389 , toReply = 0 / totalTransactions = 1617140
iota-mainnet-node | 06/25 16:11:17.660 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3439 , toReply = 0 / totalTransactions = 1618860
iota-mainnet-node | 06/25 16:11:32.661 [pool-3-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3613 , toReply = 0 / totalTransactions = 1621580
```

Node info
```
"appName": "IRI",
  "appVersion": "1.4.2.4",
  "jreAvailableProcessors": 2,
  "jreFreeMemory": 166550136,
  "jreVersion": "1.8.0_171",
  "jreMaxMemory": 7635730432,
  "jreTotalMemory": 2247098368,
  "latestMilestone": "YRIW9YFDSRGX9YMHHIIWGVJQOPFSWAMVXFEEZMLOCXKKCDEURLHNQEZMCHAUXCVUAZLTROTSWRDRA9999",
  "latestMilestoneIndex": 559120,
  "latestSolidSubtangleMilestone": "IOOOMBPWZKGGAL9EIQGMQRAAIUJPJ9WNGRJRHPFMMCZ9AFWKHJOBLMZZVEDMJXUBPGTRFKIRBOAJ99999",
  "latestSolidSubtangleMilestoneIndex": 427434,
  "neighbors": 2,
  "packetsQueueSize": 0,
  "time": 1529943087566,
  "tips": 1261,
  "transactionsToRequest": 3574,
  "duration": 1
```
I tried  download a full DB, but it's also stuck, but in another block. Any ideas?

### LINKED ISSUE #841: Tips Requester Thread Exception: java.lang.IllegalStateException: Queue full
### Bug description
I randomly saw this error on my node:
```
06/25 16:30:59.721 [pool-3-thread-2] ERROR com.iota.iri.network.Node - Tips Requester Thread Exception:
java.lang.IllegalStateException: Queue full
        at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[na:1.8.0_171]
        at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[na:1.8.0_171]
        at com.iota.iri.network.TCPNeighbor.send(TCPNeighbor.java:91) ~[iri-1.5.0.jar:na]
        at com.iota.iri.network.Node.lambda$null$6(Node.java:534) ~[iri-1.5.0.jar:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_171]
        at com.iota.iri.network.Node.lambda$spawnTipRequesterThread$7(Node.java:534) ~[iri-1.5.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
```

I'm not entirely sure how this part of IRI works but @gjeee suggested it might be a multithreading issue here: https://github.com/iotaledger/iri/blob/12b46039b768e742c2e10343c24512718805172f/src/main/java/com/iota/iri/network/TCPNeighbor.java#L91

### Hardware Spec
Google Cloud 4 vCPUs, 10GB RAM

### Steps To Reproduce
Unknown

### LINKED ISSUE #937: Synchronization is stuck again
### Bug description
Sadly, I have to create another almost identical issue again. See #850 

My IOTA IRI node stopped synchronizing again after updating to version 1.5.3. Basically any restart of the node gets the synchronization stuck.

I downloaded the latest database snapshot several times but the synchronization never continues. As recommended by neighbors I also left the node running for many hours (48h at least). The `Latest Milestone Tracker` keeps reporting that the latest milestone has changed yet the `solid milestone index` still does not change. I also started the node with the flag `--revalidate` as recommended by members in the IOTA Discord chat. When doing so it keeps updating the `solid milestone index` for a few blocks, but then again stops updating.

### Hardware Spec
The node is running inside of a Docker container (CentOS 7.5) on-top of a virtual machine (CentOS 7.5).
16 cores (Intel Xeon E5)
16 GB memory
80 GB SSD (Raid5, 500MB/s each)

### Steps To Reproduce
1. Download the latest database snapshot from `http://db.iota.partners/IOTA.partners-mainnetdb.tar.gz`
(Installation is done according to http://iota.partners/, except that IRI is running inside of a Docker container)
2. Unarchive the database
3. Start the node with the `--revalidate` flag (inside of a Docker container?)

### Expected behaviour
The node must update the `latestSolidSubtangleMilestone` after connecting to its peers.

### Actual behavior
The node connects to its peers, reports that the `latestSubtangleMilestone` has changed but never updates the `latestSolidSubtangleMilestone`.

### Errors
The node does not report any error messages (except that 1 neighbors is down) but suddenly stops updating the `latestSolidSubtangleMilestone`.

It would be great if a developer could look into this. It is easily reproducible. I have 2 nodes running in 2 different datacenters with the same issue:

**Node 1** (newly downloaded IOTA database)
```
{
  "appName": "IRI",
  "appVersion": "1.5.3",
  "jreAvailableProcessors": 16,
  "jreFreeMemory": 1311126024,
  "jreVersion": "1.8.0_181",
  "jreMaxMemory": 6442450944,
  "jreTotalMemory": 2191523840,
  "latestMilestone": "NARF9DKJYFJCSCGDQPBWKQNQMWFSFODP9XH9EZPOKAMLKCTRATLFTHY9BNDHECRIFHEABZ9GGCWJZ9999",
  "latestMilestoneIndex": 678146,
  "latestSolidSubtangleMilestone": "TPGQFIXBPH9NMSQIXDWWDE9AJNPJGLBCUQQYJEOHXHGOVJKNRB9ZFRHGKOLCVBWSABHNT9YLCPMFZ9999",
  "latestSolidSubtangleMilestoneIndex": 677946,
  "milestoneStartIndex": 590000,
  "neighbors": 7,
  "packetsQueueSize": 0,
  "time": 1534171128198,
  "tips": 926,
  "transactionsToRequest": 157,
  "duration": 0
}
```

**Node 2** (running for 72 hours at least)
```
{
  "appName": "IRI",
  "appVersion": "1.5.3",
  "jreAvailableProcessors": 16,
  "jreFreeMemory": 1071203280,
  "jreVersion": "1.8.0_181",
  "jreMaxMemory": 6442450944,
  "jreTotalMemory": 2168455168,
  "latestMilestone": "GMNIBKEOINRFBIHZTLCBXOOECRCEBV9V9A9GK9UCRJSHASEIGDTPNKSQWPAQRAQKPGYK9AWMOXFOZ9999",
  "latestMilestoneIndex": 678035,
  "latestSolidSubtangleMilestone": "D9TYNLMQFIMHQQMDPVADNPYSZFVRUJECXJMTTLUW9XXLAU9QSJCMNCXTA9CVVTCFF9IYCTBOQD9NA9999",
  "latestSolidSubtangleMilestoneIndex": 669920,
  "milestoneStartIndex": 590000,
  "neighbors": 4,
  "packetsQueueSize": 0,
  "time": 1534169494229,
  "tips": 9695,
  "transactionsToRequest": 4,
  "duration": 1
}
```

### Other
Please find the configuration file of my node below:
```
[IRI]
PORT = 14265
UDP_RECEIVER_PORT = 14600
TCP_RECEIVER_PORT = 15600
API_HOST = 0.0.0.0
IXI_DIR = /app/iri/ixi
HEADLESS = true
DEBUG = false
TESTNET = false
DB_PATH = /data/iri
RESCAN_DB = false
ZMQ_ENABLED = true
ZMQ_PORT = 5556

REMOTE_LIMIT_API = "removeNeighbors, addNeighbors, getNeighbors, setApiRateLimit"

NEIGHBORS = tcp://host01.domain.tld:15600 tcp://host02.domain.tld:15600 tcp://host03.domain.tld:15600  udp://host04.domain.tld:14400 udp://host05.domain.tld:14600
```

Please find the Dockerfile below:
```
FROM centos:centos7

ENV IRI_VERSION="1.5.3"
ENV IRI_CHECKSUM="61ede1b4f71074054dd87bdd16fe4ad9c76a3cca136bfb87f07381cdb1fc3f38"

ENV JDK_VERSION="8"
ENV JDK_RELEASE="181"
ENV JDK_CHECKSUM="1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3"

EXPOSE 14265/tcp
EXPOSE 14600/udp
EXPOSE 15600/tcp

RUN yum -y install wget && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN install --directory --owner=root --group=root --mode=0755 /data/iri/

VOLUME /data/iri/

RUN install --directory --owner=root --group=root --mode=0755 /app/jdk/

RUN wget -q -O /tmp/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.tar.gz \
    --header 'Cookie:oraclelicense=accept-securebackup-cookie' \
    http://download.oracle.com/otn-pub/java/jdk/${JDK_VERSION}u${JDK_RELEASE}-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.tar.gz; \
    echo "${JDK_CHECKSUM}  /tmp/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.tar.gz" > /tmp/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.checksum; \
    sha256sum -c /tmp/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.checksum || exit 1; \
    tar xzf /tmp/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.tar.gz -C /app/jdk/; \
    rm -f /tmp/jdk-${JDK_VERSION}u${JDK_RELEASE}-linux-x64.*

RUN chown -R root:root /app/jdk/

RUN ln -s /app/jdk/jdk1.${JDK_VERSION}.0_${JDK_RELEASE} /app/jdk/current

ENV JAVA_HOME /app/jdk/current

RUN install --directory --owner=root --group=root --mode=0755 /app/iri/bin && \
    install --directory --owner=10000 --group=10000 --mode=0755 /app/iri/ixi

RUN useradd -c 'iri' -m -p '!' -u 10000 -s '/bin/bash' iri

RUN wget -q -O /app/iri/bin/iri-${IRI_VERSION}.jar \
    https://github.com/iotaledger/iri/releases/download/v${IRI_VERSION}/iri-${IRI_VERSION}.jar && \
    echo "${IRI_CHECKSUM}  /app/iri/bin/iri-${IRI_VERSION}.jar" > /app/iri/bin/iri-${IRI_VERSION}.checksum && \
    sha256sum -c /app/iri/bin/iri-${IRI_VERSION}.checksum || exit 1 && \
    rm -f /app/iri/bin/iri-${IRI_VERSION}.checksum

RUN ln -s /app/iri/bin/iri-${IRI_VERSION}.jar /app/iri/bin/iri.jar

RUN chown -R root:root /app/iri/

RUN install --directory --owner=root --group=root --mode=0755 /app/iri/conf

COPY iri.ini /app/iri/conf/

USER iri
ENTRYPOINT ["/app/jdk/current/bin/java", "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableAttachMechanism", "-XX:InitiatingHeapOccupancyPercent=60", "-XX:G1MaxNewSizePercent=75", "-XX:MaxGCPauseMillis=10000", "-XX:+UseG1GC", "-Xms2048m", "-Xmx6144m", "-Djava.net.preferIPv4Stack=true", "-jar", "/app/iri/bin/iri.jar", "-c", "/app/iri/conf/iri.ini", "--remote"]
```

### PR DESCRIPTION
**Pull request by gjeee**
# Description

```
 @Override
    public void send(DatagramPacket packet) {
        if (sendQueue.remainingCapacity() == 0) {
            sendQueue.poll();
        }
        byte[] bytes = packet.getData().clone();
        sendQueue.add(ByteBuffer.wrap(bytes));
}
```

The sendQueue which is used in #TCPNeighbor.send() is a [ArrayBlockingQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ArrayBlockingQueue.html) with a capacity of 10. I think this method needs a lock so that the poll() and add() are done synchronized (to prevent queue full exceptions), since three threads are calling this send method:
1. spawnReplyToRequestThread: `replyToRequestFromQueue -> replyToRequest -> sendPacket -> neighbor.send(sendingPacket);`
2. spawnTipRequesterThread:  `neighbors.forEach(n -> n.send(tipRequestingPacket));`
3. spawnBroadcasterThread:  `sendPacket ->  neighbor.send(sendingPacket);`

Although #Node.sendPacket() also contains a [lock](https://github.com/iotaledger/iri/blob/08c2cb9a0ff268001c77916c8d123956ddcbd889/src/main/java/com/iota/iri/network/Node.java#L465), the spawnTipRequesterThread does not provide such a mechanism. This can also explain that sometimes intermediate milestones are skipped (because of these dropouts).

Fixes #841 
Fixes #937 
Fixes #837 

It also might be useful to increase the size of this queue, so when people are syncing not too many are dropped.

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

No.

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/network/TCPNeighbor.java [hunk 1]
```diff
@@ -19,7 +19,7 @@
     private static final Logger log = LoggerFactory.getLogger(Neighbor.class);
     private int tcpPort;
 
-    private final ArrayBlockingQueue<ByteBuffer> sendQueue = new ArrayBlockingQueue<>(10);
+    private final ArrayBlockingQueue<ByteBuffer> sendQueue = new ArrayBlockingQueue<>(1000);
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/network/TCPNeighbor.java]: This change has to be tested...
@gjeee do you see the queue filling up?

File: src/main/java/com/iota/iri/network/TCPNeighbor.java [hunk 2]
```diff
@@ -84,11 +84,14 @@ public void setSink(Socket sink) {
      */
     @Override
     public void send(DatagramPacket packet) {
-        if (sendQueue.remainingCapacity() == 0) {
-            sendQueue.poll();
+        synchronized (sendQueue) {
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/network/TCPNeighbor.java]: That is the quickest solution. Kinda patchy but this is the best thing to do right now.
@akashgoswami is currently working on a new implementation of networking which will solve these issues

**Comment by gjeee** [comment]
ok i set the capacity back to 10 and added some log statements to see how this queue behaves.
i tested it and the maximum it reached was 6 and only just after start-up. after a while it is almost always 0. however i only have 1 tcp neighbor and was almost completely synched when i restarted.

i guess it can start dropping msgs if you have more tcp neighbors and when you startup with a more out-of-sync node.

@grittibaenz (he has 5 tcp neighbors) will test this patch as well and report on the findings.

**Comment by gjeee** [comment]
well i was too premature, in my setup after a while it start dropping (like crazy)....it happened around 15:21:38
pls check my logs
[sendQueue.txt](https://github.com/iotaledger/iri/files/2310517/sendQueue.txt)

this explains a lot if weird syncing issues with nodes with tcp-neighbors

**Comment by grittibaenz** [comment]
@gjeee asked me to run IRI 1.5.3 + 940.patch. I left the node running for 20 minutes. It produced `26038` messages with the line:
```
08/22 15:38:22.550 [pool-3-thread-1] INFO  com.iota.iri.network.Neighbor - Sendqueue full...dropped 1 tx
...
08/22 15:58:13.659 [pool-3-thread-1] INFO  com.iota.iri.network.Neighbor - Sendqueue full...dropped 1 tx
```

I have 8 neighbors, 5 with TCP and 3 UDP. Please let me know if you need more details.

**Comment by gjeee** [comment]
i see this has been merged. however the latest commit still contains superfluous log statements. shall i do a new PR? @GalRogozinski
