### PR TITLE
Don't start node if local snapshot is loaded but there is no spent ad…

### LINKED ISSUE #1260: Node should only start with the local snapshot spent address file present
### Description
Node should only start up successfully when the file that persists and updates spent addresses for an LS node is present. This should be a simple start-up check that returns an error. 

### Requirements
With file
1. I run a node and the spent addresses file the LS node updates is present.
2. The node starts as usual.

Without file
1. I run a node and the spent addresses file the LS node updates is present.
2. The node fails to run, stating that file <file name>.<file extension> is missing in <folder.

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description
Ensures that we have spent addresses data before we load a local snapshot

Fixes #1260 

## Type of change
- Bug fix
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

Isolated node has been run with and without spent address db to ensure that the node exits

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by GalRogozinski** [comment]
Note that this may break local unit tests if you have snapshot files in your CWD but no spent address db

File: src/main/java/com/iota/iri/service/spentaddresses/SpentAddressesProvider.java [hunk 1]
```diff
@@ -8,6 +8,15 @@
  * Find, mark and store spent addresses
  */
 public interface SpentAddressesProvider {
+    /**
+     * Folder where we store spent address data
+     */
+    String SPENT_ADDRESSES_DB = "spent-addresses-db";
```
Comment (alon-e) [inline src/main/java/com/iota/iri/service/spentaddresses/SpentAddressesProvider.java]: see #1268

Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/spentaddresses/SpentAddressesProvider.java]: yeah, I don't want to make it configurable for this release

I want to raise #1268 in a team meeting and decide on the best way to approach it.
Worst case we will add it on a later version
