### PR TITLE
`--remote` flag will enable API interface to all hosts

### LINKED ISSUE #952: --remote flag replaced for --api-host in PR #910
### Bug description
`--remote` switch removal broke backwards compatibility.

### Expected behaviour
API listener binds on `0.0.0.0`.

### Actual behaviour
API listener binds only to `127.0.0.1`.

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description
The `--remote` flag that opens the api interface to all hosts was accidentally removed. It is now returned

Fixes #952 

## Type of change
- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?
Unit tests were added

- `testRemoteFlag()` ascertains that `api_host == 0.0.0.0`
- `testIniParsingTestnet()` now makes sure that `REMOTE` in INI has no effect (This conforms to backwards compatibility)

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/conf/BaseIotaConfig.java [hunk 1]
```diff
@@ -31,6 +32,8 @@
     protected int maxGetTrytes = Defaults.MAX_GET_TRYTES;
     protected int maxBodyLength = Defaults.MAX_BODY_LENGTH;
     protected String remoteAuth = Defaults.REMOTE_AUTH;
+    //We don't have a REMOTE config but we have a remote flag. We must add a field for JCommander
+    private boolean remote;
```
[the remark this answers is not in the document]
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/conf/BaseIotaConfig.java]: Must be used becuase of JCommander

File: src/test/java/com/iota/iri/conf/ConfigTest.java [hunk 2]
```diff
@@ -207,6 +216,8 @@ public void testIniParsingTestnet() throws Exception {
                 .append("NUMBER_OF_KEYS_IN_A_MILESTONE = 3").append(System.lineSeparator())
                 .append("DONT_VALIDATE_TESTNET_MILESTONE_SIG = true").append(System.lineSeparator())
                 .append("TIPSELECTION_ALPHA = 1.1").append(System.lineSeparator())
+                //doesn't do anything
+                .append("REMOTE")
```
Comment (alon-e) [inline src/test/java/com/iota/iri/conf/ConfigTest.java]: I think this will be confusing - there is no real reason why `REMOTE` should not work in the config file - I would not call that "not backward compatible".

Comment (GalRogozinski) [reply src/test/java/com/iota/iri/conf/ConfigTest.java]: The thing is that I don't know if it is correct that you have two ways to manipulate API_HOST...
I can totally imagine someone setting his API host to some IP. Later on he will google how to open his node to the world and add the REMOTE option. He won't notice the API_HOST becuase there are so many configs...

The same problem can also exist with flags, but it is less bad since you have to retype them.

Comment (alon-e) [reply src/test/java/com/iota/iri/conf/ConfigTest.java]: ok, I agree for now.
Can you open an issue about that then?

Comment (GalRogozinski) [reply src/test/java/com/iota/iri/conf/ConfigTest.java]: I added a comment on https://github.com/iotaledger/iri/issues/931 regarding this problem.
