### PR TITLE
Caches the reply to request tx to avoid redundant processing

### LINKED ISSUE #586: Neighbors making me fall out of sync due to large ToReply queue
### Bug description

**When syncing with other "new" nodes they request so many TX that my own node will fall out of sync.**

### Steps To Reproduce
**1.**  Add new node with no database to neighbor list, add via UDP or TCP.
**2.** Watch logs to see toProcess and toReply climb to 1,000.
**3.** Check node Sync, either:
 
_A._ The node will be stuck at a milestone and not ever update the milestone or subtangle milestone.
_B._ The milestone will continue to update while the subtangle milestone does not.
_C._ The node will completely freeze and essentially, do nothing.

### Expected behaviour
My node should stay in sync, while helping as _best I can_ with other nodes to get in sync as well.

### Actual behavior

Node falls out of sync. 

_My guess this it do to processing the receiving thread so much that nothing else can get done in the IRI._

### Errors

Below is 2 examples, 1 from a node that continues to update its milestone, and the other from a node that is "stuck" at a milestone.

```

  "appName": "IRI",
  "appVersion": "1.4.2.2",
  "jreAvailableProcessors": 6,
  "jreFreeMemory": 399738352,
  "jreVersion": "1.8.0_161",
  "jreMaxMemory": 1860698112,
  "jreTotalMemory": 1564999680,
  "latestMilestone": "VCBUMQSHUFFQENKOVRRKHHVNZULEGKFXTNPAHWZAPKEB9ZIJWUUQIMWBBSKWDOHTNGOPYKEHCJIZA9999",
  "latestMilestoneIndex": 379712,
  "latestSolidSubtangleMilestone": "VCBUMQSHUFFQENKOVRRKHHVNZULEGKFXTNPAHWZAPKEB9ZIJWUUQIMWBBSKWDOHTNGOPYKEHCJIZA9999",
  "latestSolidSubtangleMilestoneIndex": 379712,
  "neighbors": 10,
  "packetsQueueSize": 0,
  "time": 1521509279408,
  "tips": 143,
  "transactionsToRequest": 114,
  "duration": 0


  "appName": "IRI",
  "appVersion": "1.4.2.2",
  "jreAvailableProcessors": 6,
  "jreFreeMemory": 304821536,
  "jreVersion": "1.8.0_161",
  "jreMaxMemory": 1860698112,
  "jreTotalMemory": 1817706496,
  "latestMilestone": "LXMZVYSLHPAAKVROMCYSQFRN9LDZHIWQLHNSCJCBWFISOYIOCRMTBYAYIDTIIGGWDWMNVVGUMUAB99999",
  "latestMilestoneIndex": 379724,
  "latestSolidSubtangleMilestone": "UUICTDLZVGKYOS9QX9CSALEDSNAKVNZJE9VEKGLUEMVFZDLWRGVC99XIZRIOCWW9KNAMHEOLQFDS99999",
  "latestSolidSubtangleMilestoneIndex": 379716,
  "neighbors": 10,
  "packetsQueueSize": 0,
  "time": 1521508866582,
  "tips": 5194,
  "transactionsToRequest": 53,
  "duration": 1
```

### As you can see above, the milestone continues to update, yet my subtangle milestone does not. This is because the IRI cares more about replying than keeping itself in sync.

You can see transactions build up in the ToProcess queue until it falls behind.

**ToReply and ToProcess will stay at a steady 1,000 no matter what. ~ Give or take  #10**

_In my opinion we should be able to limit the Receiving threads of UDP/TCP so they do not make our nodes go out of sync._

_Or better yet, make replying the least priority compared to requesting, broadcasting, and procession._

```
Mar 19 18:14:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:14:43.711 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 945 , toBroadcast = 0 , toRequest = 45 , toReply = 1000 / totalTransactions = 12525752
Mar 19 18:14:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:14:53.712 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 907 , toBroadcast = 0 , toRequest = 42 , toReply = 1000 / totalTransactions = 12525761
Mar 19 18:15:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:03.713 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 832 , toBroadcast = 0 , toRequest = 39 , toReply = 1000 / totalTransactions = 12525768
Mar 19 18:15:06 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:06.203 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379719 to #379720
Mar 19 18:15:11 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:11.215 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379720 to #379721
Mar 19 18:15:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:13.716 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 997 , toBroadcast = 0 , toRequest = 41 , toReply = 1000 / totalTransactions = 12525776
Mar 19 18:15:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:23.718 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 982 , toBroadcast = 0 , toRequest = 39 , toReply = 999 / totalTransactions = 12525781
Mar 19 18:15:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:33.721 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 998 , toBroadcast = 0 , toRequest = 43 , toReply = 1000 / totalTransactions = 12525787
Mar 19 18:15:34 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:34.249 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 50000/0

```

**## Below you can see, when I remove the neighbor my sync continues:**

```
Mar 19 18:35:22 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:22.707 [XNIO-1 task-17] INFO  com.iota.iri.service.API - Removing neighbor: xxxx.xxxxx.xx
Mar 19 18:35:22 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:22.708 [XNIO-1 task-17] INFO  com.iota.iri.service.API - Removing neighbor: xxxx.xxxxx.xx
Mar 19 18:35:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:23.950 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 997 , toBroadcast = 0 , toRequest = 64 , toReply = 1000 / totalTransactions = 12526704
Mar 19 18:35:25 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:25.035 [XNIO-1 task-19] INFO  com.iota.iri.service.API - Removing neighbor: xxxx.xxxxx.xx
Mar 19 18:35:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:33.951 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 181 , toBroadcast = 0 , toRequest = 68 , toReply = 370 / totalTransactions = 12526712
Mar 19 18:35:36 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:36.805 [XNIO-1 task-22] INFO  com.iota.iri.service.API - Adding neighbor: xxxx.xxxxx.xx
Mar 19 18:35:41 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:41.288 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379734 to #379735
Mar 19 18:35:42 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:42.728 [XNIO-1 task-21] INFO  com.iota.iri.service.API - Removing neighbor: xxxx.xxxxx.xx
Mar 19 18:35:42 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:42.735 [XNIO-1 task-13] INFO  com.iota.iri.service.API - Removing neighbor: xxxx.xxxxx.xx
Mar 19 18:35:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:43.954 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 61 , toReply = 0 / totalTransactions = 12526730
Mar 19 18:35:45 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:45.153 [Solid Milestone Tracker] INFO  com.iota.iri.Milestone - Latest SOLID SUBTANGLE milestone has changed from #379716 to #379717
Mar 19 18:35:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:35:53.955 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 62 , toReply = 0 / totalTransactions = 12526739
Mar 19 18:36:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:36:03.957 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 64 , toReply = 0 / totalTransactions = 12526746
Mar 19 18:36:05 xxxx.xxxxx.xx IRI[23941]: 03/19 18:36:05.444 [Solid Milestone Tracker] INFO  com.iota.iri.Milestone - Latest SOLID SUBTANGLE milestone has changed from #379717 to #379721
Mar 19 18:36:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:36:13.958 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 61 , toReply = 0 / totalTransactions = 12526756
```

**# _Additional logs/info:_**
```

 "neighbors": [
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 57684,
      "numberOfRandomTransactionRequests": 8330,
      "numberOfNewTransactions": 3495,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 73309,
      "connectionType": "tcp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 57591,
      "numberOfRandomTransactionRequests": 6709,
      "numberOfNewTransactions": 1824,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 60450,
      "connectionType": "tcp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",,
      "numberOfAllTransactions": 59775,
      "numberOfRandomTransactionRequests": 5404,
      "numberOfNewTransactions": 10716,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 58920,
      "connectionType": "udp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 60403,
      "numberOfRandomTransactionRequests": 6438,
      "numberOfNewTransactions": 290,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 60528,
      "connectionType": "tcp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 58901,
      "numberOfRandomTransactionRequests": 6560,
      "numberOfNewTransactions": 714,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 60096,
      "connectionType": "tcp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 61151,
      "numberOfRandomTransactionRequests": 6570,
      "numberOfNewTransactions": 4545,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 60690,
      "connectionType": "udp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 61226,
      "numberOfRandomTransactionRequests": 6531,
      "numberOfNewTransactions": 14731,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 60971,
      "connectionType": "udp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 52310,
      "numberOfRandomTransactionRequests": 4861,
      "numberOfNewTransactions": 9,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 64405,
      "connectionType": "udp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",,
      "numberOfAllTransactions": 271852,
      "numberOfRandomTransactionRequests": 18,
      "numberOfNewTransactions": 5,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 77482,
      "connectionType": "udp"
    },
    {
      "address": "xxx.xxx.xxx.xxx",
      "numberOfAllTransactions": 603,
      "numberOfRandomTransactionRequests": 0,
      "numberOfNewTransactions": 5,
      "numberOfInvalidTransactions": 0,
      "numberOfSentTransactions": 309,
      "connectionType": "udp"

```

```
ar 19 18:14:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:14:43.711 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 945 , toBroadcast = 0 , toRequest = 45 , toReply = 1000 / totalTransactions = 12525752
Mar 19 18:14:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:14:53.712 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 907 , toBroadcast = 0 , toRequest = 42 , toReply = 1000 / totalTransactions = 12525761
Mar 19 18:15:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:03.713 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 832 , toBroadcast = 0 , toRequest = 39 , toReply = 1000 / totalTransactions = 12525768
Mar 19 18:15:06 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:06.203 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379719 to #379720
Mar 19 18:15:11 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:11.215 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379720 to #379721
Mar 19 18:15:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:13.716 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 997 , toBroadcast = 0 , toRequest = 41 , toReply = 1000 / totalTransactions = 12525776
Mar 19 18:15:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:23.718 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 982 , toBroadcast = 0 , toRequest = 39 , toReply = 999 / totalTransactions = 12525781
Mar 19 18:15:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:33.721 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 998 , toBroadcast = 0 , toRequest = 43 , toReply = 1000 / totalTransactions = 12525787
Mar 19 18:15:34 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:34.249 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 50000/0
Mar 19 18:15:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:43.723 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 999 , toBroadcast = 0 , toRequest = 42 , toReply = 1000 / totalTransactions = 12525795
Mar 19 18:15:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:15:53.725 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 957 , toBroadcast = 0 , toRequest = 39 , toReply = 1000 / totalTransactions = 12525800
Mar 19 18:16:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:03.726 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 979 , toBroadcast = 0 , toRequest = 36 , toReply = 1000 / totalTransactions = 12525807
Mar 19 18:16:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:13.728 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 924 , toBroadcast = 0 , toRequest = 37 , toReply = 1000 / totalTransactions = 12525810
Mar 19 18:16:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:23.729 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 899 , toBroadcast = 0 , toRequest = 35 , toReply = 1000 / totalTransactions = 12525820
Mar 19 18:16:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:33.731 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1000 , toBroadcast = 0 , toRequest = 35 , toReply = 1000 / totalTransactions = 12525827
Mar 19 18:16:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:43.007 [XNIO-1 task-10] INFO  com.iota.iri.service.API - Adding neighbor: udp://xxx.xxx.xxx
Mar 19 18:16:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:43.732 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 960 , toBroadcast = 0 , toRequest = 35 , toReply = 1000 / totalTransactions = 12525835
Mar 19 18:16:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:16:53.733 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 997 , toBroadcast = 0 , toRequest = 38 , toReply = 1000 / totalTransactions = 12525840
Mar 19 18:17:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:03.735 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 878 , toBroadcast = 0 , toRequest = 38 , toReply = 1000 / totalTransactions = 12525848
Mar 19 18:17:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:13.735 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 868 , toBroadcast = 0 , toRequest = 41 , toReply = 1000 / totalTransactions = 12525857
Mar 19 18:17:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:23.737 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 739 , toBroadcast = 0 , toRequest = 42 , toReply = 1000 / totalTransactions = 12525863
Mar 19 18:17:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:33.738 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1000 , toBroadcast = 0 , toRequest = 40 , toReply = 1000 / totalTransactions = 12525873
Mar 19 18:17:39 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:39.536 [XNIO-1 task-29] INFO  com.iota.iri.service.API - Removing neighbor: XXX.XXX.XXX
Mar 19 18:17:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:43.739 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 940 , toBroadcast = 0 , toRequest = 44 , toReply = 1000 / totalTransactions = 12525884
Mar 19 18:17:48 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:48.701 [XNIO-1 task-32] INFO  com.iota.iri.service.API - Removing neighbor: XXX.XXXX.XXXX
Mar 19 18:17:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:17:53.741 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 966 , toBroadcast = 0 , toRequest = 43 , toReply = 999 / totalTransactions = 12525891
Mar 19 18:18:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:03.742 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 989 , toBroadcast = 0 , toRequest = 43 , toReply = 998 / totalTransactions = 12525903
Mar 19 18:18:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:13.743 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 995 , toBroadcast = 0 , toRequest = 43 , toReply = 1000 / totalTransactions = 12525907
Mar 19 18:18:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:23.745 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 985 , toBroadcast = 0 , toRequest = 45 , toReply = 998 / totalTransactions = 12525914
Mar 19 18:18:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:33.746 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 985 , toBroadcast = 0 , toRequest = 49 , toReply = 1000 / totalTransactions = 12525928
Mar 19 18:18:36 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:36.248 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379721 to #379723
Mar 19 18:18:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:43.747 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 983 , toBroadcast = 0 , toRequest = 45 , toReply = 1000 / totalTransactions = 12525934
Mar 19 18:18:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:18:53.748 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 871 , toBroadcast = 0 , toRequest = 47 , toReply = 1000 / totalTransactions = 12525947
Mar 19 18:19:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:03.750 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 983 , toBroadcast = 0 , toRequest = 48 , toReply = 1000 / totalTransactions = 12525952
Mar 19 18:19:04 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:04.199 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 50000/0
Mar 19 18:19:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:13.751 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 953 , toBroadcast = 0 , toRequest = 51 , toReply = 1000 / totalTransactions = 12525961
Mar 19 18:19:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:23.752 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 1000 , toBroadcast = 0 , toRequest = 50 , toReply = 1000 / totalTransactions = 12525964
Mar 19 18:19:33 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:33.754 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 927 , toBroadcast = 0 , toRequest = 52 , toReply = 999 / totalTransactions = 12525966
Mar 19 18:19:43 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:43.755 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 879 , toBroadcast = 0 , toRequest = 54 , toReply = 1000 / totalTransactions = 12525975
Mar 19 18:19:53 xxxx.xxxxx.xx IRI[23941]: 03/19 18:19:53.756 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 927 , toBroadcast = 0 , toRequest = 55 , toReply = 1000 / totalTransactions = 12525981
Mar 19 18:20:03 xxxx.xxxxx.xx IRI[23941]: 03/19 18:20:03.757 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 890 , toBroadcast = 0 , toRequest = 57 , toReply = 1000 / totalTransactions = 12526004
Mar 19 18:20:05 xxxx.xxxxx.xx IRI[23941]: 03/19 18:20:05.565 [XNIO-1 task-24] INFO  com.iota.iri.service.API - Removing neighbor: udp://xxx.xxx.xxx
Mar 19 18:20:06 xxxx.xxxxx.xx IRI[23941]: 03/19 18:20:06.266 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #379723 to #379724
Mar 19 18:20:13 xxxx.xxxxx.xx IRI[23941]: 03/19 18:20:13.759 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 909 , toBroadcast = 0 , toRequest = 56 , toReply = 999 / totalTransactions = 12526009
Mar 19 18:20:23 xxxx.xxxxx.xx IRI[23941]: 03/19 18:20:23.760 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 939 , toBroadcast = 0 , toRequest = 56 , toReply = 1000 / totalTransactions = 12526012
```

Thanks,

Additional questions: PM me on Discord at: Typpi#3906 👍 💯

### PR DESCRIPTION
**Pull request by alon-e**
# Description
analyzing what happens when a new node tries to sync:

let `N` be the synced node & `n` be the new node.
```
N                      n
    <- ?|h(tx)   -      //n requests tx
    - tx|h(?)   ->      //N replies with tx
    <- tx|h(tx2) -      //n, which just found out about `tx` broadcasts it to every one (and request something else)
```
so in this case `N` will analyze the last packet - i.e. will hash it to check MWM etc.
this is redundant in this case, and is a burdun on `N`.
in my test (8 core) both nodes consumed 400%.
and profiling showed 85% of the CPU is spent in `Curl.transform`

proposed solution:
however, it's simple to see that `n->N tx` can be anticipated, I mean `N` just sent it to `n`.
so y proposal is for `N` to add `tx` to its `recentSeenBytes` list as if it already received it.
this would make `N` skip the hashing and validation.

---
this result is dramatic:
1. CPU consumption: `N` ~75% ; `n` ~550%
2. profiling: 27% transform, 22% rock.get, 15% UDP socket! - much more balanced.
3. `n` syncs 150% faster.
4. while `toReply` still gets high, the `toProcess` stays low.

Fixes #586 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

- Testing 2 nodes - `N` synced and `n` a fresh node, and comparing CPU usage and hotspots.

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/network/Node.java [hunk 1]
```diff
@@ -224,14 +224,11 @@ public void preProcessReceivedData(byte[] receivedData, SocketAddress senderAddr
                 try {
 
                     //Transaction bytes
-
-                    MessageDigest digest = MessageDigest.getInstance("SHA-256");
-                    digest.update(receivedData, 0, TransactionViewModel.SIZE);
-                    ByteBuffer byteHash = ByteBuffer.wrap(digest.digest());
+                    ByteBuffer digest = getBytesDigest(receivedData);
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/network/Node.java]: like
