### PR TITLE
Will fix #1231: ZMQ publishes to TCP and IPC instead of just one of them

### LINKED ISSUE #1231: ZMQ publishes to TCP and IPC instead of just one of them
### Bug description
Currently IRI's zmq socket binds to both TCP (non configurable) and IPC (by default configuration).
This seems to be confusing. Some people may not want TCP, or not need IPC by default.
We need to be able to configure all the sockets that ZMQ publishes to.
 
### IRI version
1.5.5

### Expected behaviour
One can configure exactly what sockets the ZMQ streams publish to.

### Actual behavior
TCP is always being published to and is non-configurable.

### PR DESCRIPTION
**Pull request by legacycode**
# Description

This change makes it possible to run ZMQ on IPC or/and TCP socket:

`--zmq-enable-tcp true` - will run ZMQ on TCP default port 5556
`--zmq-enable-ipc true` - will run ZMQ on IPC default socket ipc://iri
`--zmq-enabled true` - will run ZMQ as before on TCP and IPC socket for backward compatibility (should be removed in the future)

Fixes #1231: ZMQ publishes to TCP and IPC instead of just one of them

## Type of change

- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?
Implemented new unit tests ZMQConfigTest.java for testing command line parameters

- start iri with `--zmq-enable-tcp true` parameter and check ZMQ binds to TCP port 5556
- start iri with `--zmq-enable-ipc true` parameter and check ZMQ binds to ips socket ipc://iri
- start iri with `--zmq-enabled true` parameter and check ZMQ binds like before change

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/conf/BaseIotaConfig.java [hunk 1]
```diff
@@ -616,15 +622,48 @@ protected void setSpentAddressesDbLogPath(String spentAddressesDbLogPath) {
...
+        this.zmqEnableTcp = zmqEnableTcp;
+    }
+
+    @Override
+    public boolean isZmqEnableIpc() {
+        return zmqEnableIpc;
+    }
+
+    @JsonProperty
+    @Parameter(names = "--zmq-enable-ipc", description = ZMQConfig.Descriptions.ZMQ_ENABLE_IPC)
```
Comment (kwek20) [inline src/main/java/com/iota/iri/conf/BaseIotaConfig.java]: Please add `arity = 1`

File: src/main/java/com/iota/iri/conf/BaseIotaConfig.java [hunk 2]
```diff
@@ -616,15 +622,48 @@ protected void setSpentAddressesDbLogPath(String spentAddressesDbLogPath) {
...
+        this.zmqEnableIpc = zmqEnabled;
+    }
+
+    @Override
+    public boolean isZmqEnableTcp() {
+        return zmqEnableTcp;
+    }
+
+    @JsonProperty
+    @Parameter(names = "--zmq-enable-tcp", description = ZMQConfig.Descriptions.ZMQ_ENABLE_TCP)
```
Comment (kwek20) [inline src/main/java/com/iota/iri/conf/BaseIotaConfig.java]: Please add `arity = 1`

File: src/main/java/com/iota/iri/storage/Tangle.java [hunk 3]
```diff
@@ -107,16 +114,27 @@ public void delete(Class<?> model, Indexable index) throws Exception {
...
-            boolean success = false;
-            for(PersistenceProvider provider: this.persistenceProviders) {
-                if(success) {
-                    provider.update(model, index, item);
-                } else {
-                    success = provider.update(model, index, item);
-                }
-            }
-            return success;
+    public void update(Persistable model, Indexable index, String item) throws Exception {
```
Comment (kwek20) [inline src/main/java/com/iota/iri/storage/Tangle.java]: Although we never actually check the return of the update currently, im not sure if we should remove it. Lets wait for @GalRogozinski to come back from holiday and see what he thinks!

File: src/main/java/com/iota/iri/conf/BaseIotaConfig.java (hunk 1 above)
Comment (legacycode) [reply src/main/java/com/iota/iri/conf/BaseIotaConfig.java]: This will force setting the keyword true after --zmq-enable-ipc true. Done.

File: src/main/java/com/iota/iri/conf/BaseIotaConfig.java (hunk 2 above)
Comment (legacycode) [reply src/main/java/com/iota/iri/conf/BaseIotaConfig.java]: This will force setting the keyword true after --zmq-enable-tcp true. Done.

File: src/main/java/com/iota/iri/storage/Tangle.java (hunk 3 above)
Comment (legacycode) [reply src/main/java/com/iota/iri/storage/Tangle.java]: Please have a closer look at the old logic on creating the return value. It will return true, when only one PersistanceProviders update succseeds. Thats a lot of unneeded code that can produce issues in the future. When implementing a new return value the use case should be specified before.

**Comment by GalRogozinski** [comment]
This looks good to merge after we release 1.6.1

**Comment by GalRogozinski** [comment]
Create a new branch for 1.6.1 so this can be safely merged to `dev`
