### PR TITLE
Remove WalkValidator cache of tips that are below max depth

### LINKED ISSUE #900: TipSelection is pointing to milestones
### Bug description
**Default tip selection causes** "dispersion" of the tangle around milestones.
There are reports of blowballs being created around milestones by IRI's default tip selection.

### Steps To Reproduce
Spam an IRI node using `getTransactionsToApprove` API call for tip selection. Choose depth `3` (start the walk 3 milestones before the last one).

### Expected behaviour
Honest transactions should amass in a way that creates a tangle that advances in a clear direction.

### Actual behavior
Some transactions choose milestones in trunk and branch, creating blowballs.

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description
Removes the bad tips cache. We found that valid txs are being stored there and this disrupts tipselection.

Fixes #900

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

All unit and regression tests have passed.

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java [hunk 1]
```diff
@@ -251,9 +241,102 @@ public void failOnInconsistency() throws Exception {
...
+        final int maxAnalyzedTxs = Integer.parseInt(Configuration.BELOW_MAX_DEPTH_LIMIT);
+        TransactionViewModel tx1 = TransactionTestUtils.createBundleHead(0);
+        tx1.store(tangle);
+        tx1.setSnapshot(tangle, 92);
+
+        TransactionViewModel txBad = TransactionTestUtils.createBundleHead(0);
+        txBad.store(tangle);
+        txBad.setSnapshot(tangle, 10);
+
+        TransactionViewModel tx2 = new TransactionViewModel(TransactionViewModelTest.getRandomTransactionWithTrunkAndBranch(tx1.getHash(), tx1.getHash()),
```
Comment (karimodm) [inline src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java]: Minor thing: can we give more descriptive names to tx2 / tx3... ? Otherwise test is not that readable.

File: src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java [hunk 2]
```diff
@@ -251,9 +241,102 @@ public void failOnInconsistency() throws Exception {
...
+        Mockito.when(ledgerValidator.updateDiff(new HashSet<>(), new HashMap<>(), tx2.getHash()))
+                .thenReturn(true);
+
+        milestoneTracker.latestSolidSubtangleMilestoneIndex = 100;
+        WalkValidatorImpl walkValidator = new WalkValidatorImpl(tangle, ledgerValidator, transactionValidator,
+                milestoneTracker, 15, maxAnalyzedTxs);
+        Assert.assertFalse("Validation of tx4 succeeded but should have failed since tx is below max depth",
+                walkValidator.isValid(tx4.getHash()));
+        Assert.assertTrue("Validation of tx2 failed but should have succeeded since tx is above max depth",
+                walkValidator.isValid(tx2.getHash()));
```
Comment (karimodm) [inline src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java]: From Tx4 to reach the TxBad you need to walk branch, branch (2 steps)
From Tx2 to reach Tx1 (good) you need to walk branch or trunk (1 steps)

IMO you should construct Tx2 as close as possible to Tx4.

File: src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java (hunk 1 above)
Comment (karimodm) [reply src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java]: tx1 => txGood
tx2 => txPointsToGood
tx4 => txPointsToBad
