### PR TITLE
validate port number on addNeighbor API

### LINKED ISSUE #1678: Adding faulty neighbors no feedback and repeating errors in logs
### Bug description
Adding a neighbor with a faulty (e.g. out-of-range) port causes an exception (seen in IRI logs) and messages keep appearing about port out of range.

```
curl http://localhost:14265 -XPOST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' -d '{"command": "addNeighbors", "uris": ["tcp://google.com:90000"]}'
{"addedNeighbors":1,"duration":6}
```
IRI Logs:

```
Dec 01 20:51:43 snap docker[10915]: Exception in thread "Neighbor Router" java.lang.IllegalArgumentException: port out of range:90000
Dec 01 20:51:43 snap docker[10915]:         at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
Dec 01 20:51:43 snap docker[10915]:         at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
Dec 01 20:51:43 snap docker[10915]:         at com.iota.iri.network.NeighborRouterImpl.lambda$connectToWantedNeighbors$2(NeighborRouterImpl.java:614)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
Dec 01 20:51:43 snap docker[10915]:         at com.iota.iri.network.NeighborRouterImpl.connectToWantedNeighbors(NeighborRouterImpl.java:613)
Dec 01 20:51:43 snap docker[10915]:         at com.iota.iri.network.NeighborRouterImpl.route(NeighborRouterImpl.java:178)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Dec 01 20:51:43 snap docker[10915]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Dec 01 20:51:43 snap docker[10915]:         at java.lang.Thread.run(Thread.java:748)
Dec 01 20:51:44 snap docker[10915]: 12/01 19:51:44.123 [XNIO-1 task-2] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:51:44 snap docker[10915]: 12/01 19:51:44.747 [XNIO-1 task-3] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:51:49 snap docker[10915]: 12/01 19:51:49.129 [XNIO-1 task-12] ERROR API:291 - Unexpected API Exception: port out of range:90000
```
After a while you will notice these errors just clutter the logs and don't stop:
```
Dec 01 20:55:50 snap docker[10915]: 12/01 19:55:50.007 [XNIO-1 task-15] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:55:54 snap docker[10915]: 12/01 19:55:54.121 [XNIO-1 task-7] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:55:55 snap docker[10915]: 12/01 19:55:55.017 [XNIO-1 task-5] ERROR API:291 - Unexpected API Exception: port out of range:90000
Dec 01 20:55:59 snap docker[10915]: 12/01 19:55:59.123 [XNIO-1 task-12] ERROR API:291 - Unexpected API Exception: port out of range:90000
```

### IRI version
What version are you running?
1.8.2-RELEASE

### Hardware Spec
VPS

### Steps To Reproduce
As shown above, add a neighbor with a port out of range (>65535)

Only way to clear this seems by restarting IRI

### Expected behaviour
Reject the faulty neighbor with a message (maybe 400 bad request?)

### Actual behaviour
IRI reported neighbor added, and the rest I've explained above (+examples from the logs)

### Errors
Shown above.

### PR DESCRIPTION
**Pull request by acha-bill**
# Description

Adds port number validation to neighbour URI.
The port number is an unsigned 16-bit integer, so max is 65535. See [port](https://en.wikipedia.org/wiki/Port_(computer_networking))

Fixes #1678 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/network/NeighborRouterImpl.java [hunk 1]
```diff
@@ -839,6 +843,10 @@ private static boolean isURIValid(final URI uri) {
             log.error("'{}' is not a valid URI schema, only TCP ({}) is supported", uri, PROTOCOL_PREFIX);
```
Comment (kwek20) [inline src/main/java/com/iota/iri/network/NeighborRouterImpl.java]: The docs say its invalid when null, however we dont actually check for this. It was already like this, but can you add it anyways?

Comment (acha-bill) [reply src/main/java/com/iota/iri/network/NeighborRouterImpl.java]: nice catch
