### PR TITLE
Fail early on below max depth - WIP

### LINKED ISSUE #846: Tip-Selection freezes when stitching sidetangle to the maintangle
### Bug description
Tip-Selection/`getTransactionsToApprove` freezes on IRI nodes in the network after a sidetangle gets stitched to the main tangle. Both on IRI 1.4.x and 1.5.x
*-> It's not clear whether all 1.4.x versions tip-sel freeze.*

### Steps To Reproduce
Write a program which connects to a ZMQ feed of any IRI node and let the program up on a new sidetangle tx create a new tx referencing the sidetangle tx and a maintangle tx. (I'm happy to share the exact program if needed; idea was to get the sidetangle confirmed but rather this phenomenon unfortunately happend)

Shown in this picture (Stitching txs = orange; Note that the bigger blow ball structure is the maintangle and the leaner structure the sidetangle):
image

### Expected behaviour
Confirmation rate should be steady and tip selection shouldn't freeze.

### Actual behavior
**IRI nodes in the network** become unable to execute `getTransactionsToApprove`.
**A clear almost halt in the Tangle network was observed (obviously, because getting tips was impossible).**
Maybe having the sheer amount of txs of the sidetangle suddenly in the tip-sel might cause it to not complete.

A clear suppression of TPS can be observed in following stats (1:30pm-3:10pm):
image

Starting the stitching at 4pm resulted in a very abrupt decline of incoming txs:
image

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description
If we analyze transactions in `belowMaxDepth` and we pass a certain threshold of transactions we fail.
We also cache the analyzed transactions so that in the future we can quickly fail `belowMaxDepth`.

Fixes #846 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?

Unit tests were added:
- Long chain tangle
  - Test from genesis
  - Old snapshot index
  - New snapshot index
- Short chain tangle
  - Test from genesis
  - Old snapshot index
  - New snapshot index

# Checklist:

_Please delete items that are not relevant._

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# TODO:
1. What should be the threshold values?
MAX_CACHE_SIZE? MAX_ANALYZED_TXS?
2. Write tests for bounded set
3. Run canaries on network
4. Document `belowMaxDepth`

### CODE REVIEW

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java [hunk 1]
```diff
@@ -75,19 +82,30 @@ public boolean isValid(Hash transactionHash) throws Exception {
...
         Hash hash;
         while ((hash = nonAnalyzedTransactions.poll()) != null) {
+            if (FAILED_BELOW_MAX_DEPTH_CACHE.contains(hash)) {
+                updateCache(analyzedTransactions);
+                return true;
+            }
+            if (analyzedTransactions.size() == MAX_ANALYZED_TXS) {
+                updateCache(analyzedTransactions);
+                return true;
+            }
```
Comment (rajivshah3) [inline src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: If you wanted to make it a bit more concise, I think you could combine these into one `if` statement:
```java
if (FAILED_BELOW_MAX_DEPTH_CACHE.contains(hash) || analyzedTransactions.size() == MAX_ANALYZED_TXS) {
  updateCache(analyzedTransactions);
  return true;
}
```
But I guess that's a matter of preference

File: src/main/java/com/iota/iri/service/tipselection/WalkValidator.java [hunk 2]
```diff
@@ -1,13 +1,23 @@
...
+import java.util.LinkedHashSet;
+import java.util.Set;
 
 /**
  * Validates consistency of tails.
  */
 @FunctionalInterface
 public interface WalkValidator {
 
+    int MAX_CACHE_SIZE = 2_000_000;
```
Comment (paulhandy) [inline src/main/java/com/iota/iri/service/tipselection/WalkValidator.java]: I'd suggest to beware of the tyranny of the default magic number; wouldn't this do best as a configuration parameter with a default value?

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java [hunk 3]
```diff
@@ -26,6 +28,12 @@
  */
 public class WalkValidatorImpl implements WalkValidator {
 
+    public static final int MAX_CACHE_SIZE = 2_000_000;
+    //As long as tip selection is synchronized we are fine with the collection not being thread safe
+    private static final BoundedSet<Hash> FAILED_BELOW_MAX_DEPTH_CACHE = new BoundedSetWrapper<>(
```
Comment (th0br0) [inline src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: You're allocating a `FAILED_BELOW_MAX_DEPTH_CACHE` instance both in the impl and the interface with different evil magic numbers...

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java [hunk 4]
```diff
@@ -75,19 +82,30 @@ public boolean isValid(Hash transactionHash) throws Exception {
         return true;
     }
 
-    private boolean belowMaxDepth(Hash tip, int depth) throws Exception {
+    private boolean belowMaxDepth(Hash tip, int allowedSnapshotIndex) throws Exception {
```
Comment (th0br0) [inline src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: could we call this `minimumAllowedSnapshotIndex` or `lower...`?

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java [hunk 5]
```diff
@@ -75,19 +82,30 @@ public boolean isValid(Hash transactionHash) throws Exception {
...
             return false;
         }
         //if tip unconfirmed, check if any referenced tx is confirmed below maxDepth
         Queue<Hash> nonAnalyzedTransactions = new LinkedList<>(Collections.singleton(tip));
         Set<Hash> analyzedTransactions = new HashSet<>();
         Hash hash;
         while ((hash = nonAnalyzedTransactions.poll()) != null) {
+            if (FAILED_BELOW_MAX_DEPTH_CACHE.contains(hash)) {
+                updateCache(analyzedTransactions);
+                return true;
```
Comment (th0br0) [inline src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: if it `failed` before (I'm assuming that that is what the cahce is for) shouldn't this return `false`?

Comment (th0br0) [reply src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: Could you add a javadoc comment to this method as you're touching it?

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+
+    @Override
+    public <T> T[] toArray(T[] a) {
+        return delegate.toArray(a);
+    }
+
+    @Override
+    public boolean add(E e) {
+        if (isFull()) {
+            Iterator<E> iterator = delegate.iterator();
```
Comment (th0br0) [inline src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: this violates the description `A set that doesn't allow to add elements to it once it is full`

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+            return delegate.addAll(c);
+        }
+        else {
+            Set<E> transform = new HashSet<>(c);
+            Set<E> difference = SetUtils.difference(delegate, transform).toSet();
+            if (difference.size() > getMaxSize()) {
+                throw new IllegalArgumentException(String.format("The given set size %d is larger then maxSize %d",
+                        difference.size(), maxSize));
+            }
+            int itemsToDelete = delegate.size() + difference.size() - getMaxSize();
```
Comment (th0br0) [inline src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: this violates the description `A set that doesn't allow to add elements to it once it is full` as you're 
deleting items to make room

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java (hunk 5 above)
Comment (alon-e) [reply src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: BelowMaxDepth is a negative predicate (returning true means its "bad", failing is also bad hence true) - this is annoying to reason about and can lead to bugs. I think we should invert it. Maybe in another PR.

**Comment by rajivshah3** [comment]
When I was testing the [JAR](https://s3.eu-central-1.amazonaws.com/iotaledger-dbfiles/pre-releases/iri-1.5.2-below-maxdepth-cached-1.jar) posted by @alon-e in Discord, I think I encountereda a bug that causes an error if you try to promote a transaction. It will try to do the tip selection but then it will say “<tx hash you’re trying to promote> is below max depth” (if you have debug logging enabled) and then “entry point failed consistency check: <tx hash you’re trying to promote>”. I was only able to reproduce this with that JAR, the issue does not show up when using 1.5.1.

File: src/main/java/com/iota/iri/service/tipselection/WalkValidator.java (hunk 2 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/tipselection/WalkValidator.java]: Yup,
I wanted to get the first iteration of the PR so I only did the necessary changes. I agree with you ofc.

**Comment by alon-e** [comment]
@rajivshah3 could you give an example tx hash?

Was the original transaction sent with the new jar as well?

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java (hunk 3 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: Something got messed up with the commits I will fix it.

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java (hunk 4 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: lower

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java (hunk 6 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: Yup, copy paste mistake.
Will change description.

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java (hunk 7 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: ditto

File: src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java (hunk 1 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java]: I agree with you actually

**Comment by rajivshah3** [comment]
@alon-e it’s FYQSGNDHJNGHCTAHEYYCAQDLGAZWVTGQYVNMUNFMGYOQCKFZGSZJHUITQAZCSEFQVPFQXCQCOMII99999. I originally sent it with 1.5.1 but it has been reattached with the test jar as well

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java [hunk 8]
```diff
@@ -0,0 +1,172 @@
...
+    }
+
+    @Override
+    public boolean addAll(Collection<? extends E> c) {
+        requireCollectionIsNotAboveMaxSize(c, getMaxSize());
+        if (canCollectionBeFullyAdded(c)) {
+            return delegate.addAll(c);
+        }
+        else {
+            int itemsToDelete = delegate.size() + c.size() - getMaxSize();
```
Comment (alon-e) [inline src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: so I don't forget - please open an issue (not blocking the PR):
there may be duplicate entries in the sets `delegate` and `c` - in that case you may want to remove less items.
for example:
```
delegate = {a, b, c, d}
c = {c, d, e}
maxSize = 5
itemsToDelete = 4 +3 - 5 => 2
result: {c, d, e}
```

you could argue that it's too costly to check, but then there should be a comment explaining that heuristic.

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java [hunk 9]
```diff
@@ -0,0 +1,172 @@
...
+    }
+
+    @Override
+    public String toString() {
+        return delegate.toString();
+    }
+
+    private void requireCollectionIsNotAboveMaxSize(Collection<? extends E> c, int maxSize) {
+        if (c.size() > maxSize) {
+            throw new IllegalArgumentException(String.format("The given collection size %d is larger then maxSize %d", c.size(),
```
Comment (alon-e) [inline src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: typo: "larger then" -> "larger than"

File: src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java [hunk 10]
```diff
@@ -38,6 +40,7 @@
     public static void tearDown() throws Exception {
         tangle.shutdown();
         dbFolder.delete();
+        WalkValidatorImpl.failedBelowMaxDepthCache.clear();
```
Comment (alon-e) [inline src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java]: This will run only once per class invocation, as `tearDown` is `@AfterClass`.
is that intentional? I don't see a reason to clear the cache after disposing of the DB.

If you want to run after each test:
```
@After
    public void tearDownEach() {
        WalkValidatorImpl.failedBelowMaxDepthCache.clear();
    }
```
* tests still pass if you add this.

File: src/main/java/com/iota/iri/IRI.java [hunk 11]
```diff
@@ -330,7 +331,20 @@ private static boolean isValidated(final Configuration configuration, final Stri
...
                 configuration.put(DefaultConfSettings.MAX_PEERS, vmaxPeers);
             }
+
+            final Integer belowMaxDepthLimit = parser.getOptionValue(belowMaxDepthTxLimit);
+            if (belowMaxDepthLimit != null) {
+                configuration.put(DefaultConfSettings.BELOW_MAX_DEPTH_TRANSACTION_LIMIT,
+                        String.valueOf(belowMaxDepthLimit));
+            }
+
+            final Integer walkValidatorCache = parser.getOptionValue(walkValidatorCacheSize);
```
Comment (hmoog) [inline src/main/java/com/iota/iri/IRI.java]: maybe rename to "walkValidatorCacheSize" to be consistent with the naming in the config and Iota.java - could otherwise be mistaken with an instance of the cache (not really :) but you get the point)

Comment (GalRogozinski) [reply src/main/java/com/iota/iri/IRI.java]: The problem is that we have 2 variables with the same name...
It will be resolved when we do #724 .

File: src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java (hunk 10 above)
Comment (GalRogozinski) [reply src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java]: yes

File: src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java (hunk 8 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java]: Opened https://github.com/iotaledger/iri/issues/887
