### PR TITLE
Fix: added a buffer to LSManager

### LINKED ISSUE #1209: Transition buffer between LOCAL_SNAPSHOTS_INTERVAL_UNSYNCED and LOCAL_SNAPSHOTS_INTERVAL_SYNCED
### Description
The transition between `LOCAL_SNAPSHOTS_INTERVAL_UNSYNCED` and `LOCAL_SNAPSHOTS_INTERVAL_SYNCED` is now immediate in snapshotMilestone == latestMilestone. We could implement a buffer of 1-3 milestones in between the transition instead. 
UNSYNCED -> SYNCED transition. Maybe a "buffer" of 1-3 milestones would be better instead of snapshotMilestone == latestMilestone

**We agreed on a buffer of 5.**

### PR DESCRIPTION
**Pull request by kwek20**
# Description
To prevent jumping back and forth in and out of sync, there is now a buffer in between.
Only when the latest milestone and latest snapshot differ more than this number, we fall out of sync

Fixes #1209

## Type of change
- Enhancement (a non-breaking change which adds functionality)

# How Has This Been Tested?
Not yet tested, will request a node as soon as possible.
submitting the PR to start possible discussion about the implementation

# Checklist:
- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java [hunk 1]
```diff
@@ -51,6 +57,11 @@
      * Configuration with important snapshot related parameters.
      */
     private SnapshotConfig config;
+    
+    /**
+     * If this node is currently seen as in sync
+     */
+    private boolean isInSync;
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java]: I don't like this field:
1. It just states that this class takes more memory
2. You can easily do without it and I don't understand what value it adds
3. For this class it isn't a good example, but in general in multi threaded environments you don't want to have these kind of things since 2 different threads may modify this field.

File: src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java [hunk 2]
```diff
@@ -136,4 +146,46 @@ private void monitorThread(LatestMilestoneTracker latestMilestoneTracker) {
...
+        int latestSnapshot = snapshotProvider.getLatestSnapshot().getIndex();
+        
+        // If we are out of sync, only a full sync will get us in
+        if (!isInSync && latestIndex == latestSnapshot) {
+            isInSync = true;
+        
+        // When we are in sync, only dropping below the buffer gets us out of sync 
+        } else if (latestSnapshot < latestIndex - LOCAL_SNAPSHOT_SYNC_BUFFER) {
+            isInSync = false;
+        }
```
Comment (GalRogozinski) [inline src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java]: This could be made simpler:
```
if (latestSnapshot < latestIndex - LOCAL_SNAPSHOT_SYNC_BUFFER) {
   return false;
}
 else {
    return true;
}
```

Comment (kwek20) [reply src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java]: You cant right? Because then instead of boucing at `latestSnapshot` and `latestIndex`, it will bounce at `latestIndex - BUFFEr` and `latestsnapshot`
