### PR TITLE
Fix: Reduce db access and cpu usage needed to persist spent addresses

### LINKED ISSUE #1321: Save spent addresses after validating a bundle
### Description
Currently we persist spent addresses while pruning.
Instead we want to persist the spent address as soon as we validate a spent bundle

### Motivation
To save resources. No need to reload txs from db. No need to run bundle validator again.
We want to piggyback on existing mechanism.

### Requirements
1. After the bundle validator is invoked, we persist a spent from address
2. Remove the other paths from the code where we persist spent addresses

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description

1. While we are applying a milestone, persist validated spent addresses in the db from confirmed transactions.
2. Stop persisting them while taking a local snapshot
3. Adds unit tests while doing neccessary refactoring to make the code more testable

Fixes #1321

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?

Unit test added
Canary have been ran on the mainnet

# Checklist:

- [x] My code follows the style guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java [hunk 1]
```diff
@@ -173,11 +186,15 @@ public boolean isBalanceDiffConsistent(Set<Hash> approvedHashes, Map<Hash, Long>
...
 
-                                final List<List<TransactionViewModel>> bundleTransactions = BundleValidator.validate(
+                                final List<List<TransactionViewModel>> bundleTransactions = bundleValidator.validate(
                                         tangle, snapshotProvider.getInitialSnapshot(), transactionViewModel.getHash());
 
                                 for (final List<TransactionViewModel> bundleTransactionViewModels : bundleTransactions) {
 
+                                    //ISSUE 1008: generateBalanceDiff should be refactored so we don't have those hidden
+                                    // concerns
+                                    persistValidatedSpentAddresses(bundleTransactionViewModels);
```
Comment (alon-e) [inline src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: this appears before the `BundleValidator.isInconsistent(bundleTransactionViewModels), etc.` - it seems you are adding an address even if the signature is invalid/has no funds? (I'm looking in GH, not an IDE so I might be mistaken)

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java [hunk 2]
```diff
@@ -217,6 +234,14 @@ public boolean isBalanceDiffConsistent(Set<Hash> approvedHashes, Map<Hash, Long>
         return state;
     }
 
+    private void persistValidatedSpentAddresses(List<TransactionViewModel> bundleTransactionViewModels) throws SpentAddressesException {
+        List<Hash> spentAddresses = bundleTransactionViewModels.stream()
+                .filter(tx -> tx.value() < 0)
+                .map(TransactionViewModel::getAddressHash)
```
[the remark this answers is not in the document]
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: Agree,
I will create a SingleThreadExecutor that will perform this operation

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java [hunk 3]
```diff
@@ -153,7 +164,9 @@ public boolean isBalanceDiffConsistent(Set<Hash> approvedHashes, Map<Hash, Long>
         Map<Hash, Long> state = new HashMap<>();
         Set<Hash> countedTx = new HashSet<>();
 
-        snapshotProvider.getInitialSnapshot().getSolidEntryPoints().keySet().forEach(solidEntryPointHash -> {
+        Snapshot initialSnapshot = snapshotProvider.getInitialSnapshot();
```
[the remark this answers is not in the document]
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: This change was done as part of the following commit: https://github.com/iotaledger/iri/pull/1332/commits/faa01934606eb9990d58b66a49d44a2f6714d52b - "make the code more debuggable" (w/o changing logic).

What happened is that during a unit test I got a `NullPointerException` while mocking, but it was hard to understand what was null w/o entering debug mode.
So I quickly changed the code to make it easier to work with for the next person.
I added this change in a specialized commit. It doesn't affect any logic.

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java (hunk 1 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: It is indeed before `BundleValidator.isInconsistent(bundleTransactionViewModels)`. However, it is after `bundleValidator.validate()` which does signature validation. So I believe it is the correct place to put the method.

**Comment by GalRogozinski** [comment]
> How do you plan on tackling the transition?

_Scenario 1: an operator has a node with a correct `persisted-spent-addresses db`_:
Everytime we apply a milestone we persist spent addresses. So we are always ahead of the local snapshot, which is good imho. If someone gives this db to a friend we can be sure that it is not missing any confirmed addresses. Even ones above the LS :-)

_Scenario 2: an operator is syncing from a db_:
While pruning didn't happen the spent-addresses can be found using the old mechanism that relies on transaction metadata. Once we prune a confirmed transaction there will be a check to see if it is missing:
https://github.com/iotaledger/iri/blob/151a1bba19b0cb2dee907ca1274e480266820162/src/main/java/com/iota/iri/service/transactionpruning/jobs/MilestonePrunerJob.java#L273-L279

Note #1338 that tries to optimize this code.


Am I missing something?

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (alon-e) [reply src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: I was referencing the function "isBalanceDiffConsistent", I just cannot comment on the function declaration.

Gal & I talked and He is aware that it's triggered in every bundle validation.

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java [hunk 4]
```diff
@@ -173,11 +184,16 @@ public boolean isBalanceDiffConsistent(Set<Hash> approvedHashes, Map<Hash, Long>
...
 
-                                final List<List<TransactionViewModel>> bundleTransactions = BundleValidator.validate(
+                                final List<List<TransactionViewModel>> bundleTransactions = bundleValidator.validate(
                                         tangle, snapshotProvider.getInitialSnapshot(), transactionViewModel.getHash());
 
                                 for (final List<TransactionViewModel> bundleTransactionViewModels : bundleTransactions) {
 
+                                    //ISSUE 1008: generateBalanceDiff should be refactored so we don't have those hidden
+                                    // concerns
+                                    spentAddressesService
```
Comment (alon-e) [inline src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: small caveat, you will also scan addresses that are not spent for sure.
for example data transactions. if probably worth first filtering only negative values and if none empty submit.

**Comment by alon-e** [comment]
>Am I missing something?
I was missing the fact that we make sure again it's persisted in the pruning job.
from my understanding that `warning` should show when ppl transition to 1.6.1 if so it's worth adding to the release notes.

File: src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java (hunk 4 above)
Comment (GalRogozinski) [reply src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java]: Yup,
We are currently submitting empty sets after filtering. There is no logical fallacy but it does result in creating more objects thus increasing GC pressure...

I would say that this is a point we need to pay attention to in general with the Data Providers
